server:
  port: 6080

spring:
  application:
    name: shortLink
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.53
        username: nacos
        password: nacos

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shorturlx?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
  data:
    redis:
      host: 0.0.0.0
      port: 6379
      password: 123456
      database: 6
      jedis:
        pool:
          max-active: 8
  logging:
    level:
      root: DEBUG

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  workId: 1
  workIdBits: 10